<?php 
return array (
  'site_name' => '聚优客微信平台',
  'site_title' => '聚优客微信平台',
  'site_logo' => 'http://wx.dlwebs.com/uploads/a/admin/5/1/3/d/thumb_53c5ea25ac9e8.png',
  'site_url' => 'http://wx.dlwebs.com',
  'site_my' => '聚优客',
  'server_key' => '2315af258614bdf40697ebbdfa',
  'server_topdomain' => '180.haoid.cn',
  'connectout' => '用户请求数超过您所购买的数量，请购买！',
  'ischeckuser' => 'false',
  'reg_needmp' => 'true',
  'reg_groupid' => '1',
  'reg_validdays' => '5',
  'router_key' => '',
  'ipc' => '辽ICP备14008576号-1',
  'site_qq' => '395802201',
  'site_mp' => '13840816169',
  'baidu_map_api' => 'pDux46lHyuAMjL3fiv7rGBry',
  'site_email' => '395802201@qq.com',
  'keyword' => '聚优客微信平台-微信公众账号建设，企业微信营销，微信加粉',
  'content' => '聚优客微信平台，为您提供微信公众账号建设',
  'countsz' => '',
  'copyright' => 'Copyright © 2012-2014 聚优客版权所有',
);